# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170211_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_published',
            field=models.DateTimeField(null=True),
        ),
    ]
